services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: xray
      POSTGRES_USER: xray
      POSTGRES_PASSWORD: xray
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
