services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: xray
      POSTGRES_USER: xray
      POSTGRES_PASSWORD: xray
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:2-alpine
    command: ["--jetstream", "--store_dir=/data"]
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - natsdata:/data

volumes:
  pgdata:
  natsdata:
