import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import {
  Button,
  Card,
  Group,
  Modal,
  NumberInput,
  SegmentedControl,
  Select,
  Stack,
  Switch,
  Text,
  Title,
} from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { toJsonString } from "@bufbuild/protobuf";
import { useFetcher } from "react-router";
import { Side, OrderType, PositionSide, TimeInForce } from "../../src/gen/orderbook/v1/events_pb";
import {
  type PlaceSagaRequest,
  PlaceSagaRequestSchema,
} from "../../src/gen/saga/v1/saga_pb";
import { formatMoney, formatPrice, moneyToPrice, priceToNumber } from "~/lib/format";
import { useAccountData } from "../hooks/accountData";
import { useSharedMarketDepth } from "../hooks/marketDepth";
import { usePreviewOrderImpact } from "../hooks/usePreviewOrderImpact";

const ORDER_TYPES: Record<string, OrderType> = {
  LIMIT: OrderType.LIMIT,
  MARKET: OrderType.MARKET,
  TRAILING_STOP_MARKET: OrderType.TRAILING_STOP_MARKET,
  TRAILING_STOP_LIMIT: OrderType.TRAILING_STOP_LIMIT,
};

const TIME_IN_FORCE: Record<string, TimeInForce> = {
  GTC: TimeInForce.GTC,
  IOC: TimeInForce.IOC,
  FOK: TimeInForce.FOK,
  DAY: TimeInForce.DAY,
  AT_OPEN: TimeInForce.AT_OPEN,
  AT_CLOSE: TimeInForce.AT_CLOSE,
};

const LIMIT_TIF_OPTIONS = [
  { label: "GTC", value: "GTC" },
  { label: "IOC", value: "IOC" },
  { label: "FOK", value: "FOK" },
  { label: "DAY", value: "DAY" },
  { label: "LOO (At Open)", value: "AT_OPEN" },
  { label: "LOC (At Close)", value: "AT_CLOSE" },
];

const MARKET_TIF_OPTIONS = [
  { label: "IOC", value: "IOC" },
  { label: "FOK", value: "FOK" },
  { label: "MOO (At Open)", value: "AT_OPEN" },
  { label: "MOC (At Close)", value: "AT_CLOSE" },
];

type Mode = "SINGLE" | "BRACKET" | "OCO" | "TWAP";

// Action is the broker-standard 4-way label for single orders.
// Maps unambiguously to a (side, position_side) pair — no orthogonal
// Buy/Sell × Long/Short toggle for the user to reason about.
type Action = "BUY" | "SELL" | "SHORT" | "COVER";

// Direction is the 2-way long/short choice for bracket/OCO orders,
// which are inherently directional (a bracket is one or the other).
type Direction = "LONG" | "SHORT";

// OrderPrefill describes a single-order set-up another panel wants
// the user to start from — typically generated by Close Position
// menu entries. nonce changes on every prefill so the OrderForm
// re-applies even when the same values are pushed twice.
export type OrderPrefill = {
  symbol: string;
  action: Action;
  quantity: number;
  orderType: "MARKET" | "LIMIT";
  price?: number;
  nonce: number;
};

// ImpactRow renders a "Label: before → after (±delta)" line. When
// `before` is unavailable (margin snapshot not yet loaded) only the
// projected value shows. redIfDecrease / redIfIncrease flag warning
// states like insufficient buying power or a margin breach.
function ImpactRow({
  label,
  before,
  after,
  redIfDecrease,
  redIfIncrease,
}: {
  label: string;
  before: bigint | undefined;
  after: bigint | undefined;
  redIfDecrease?: boolean;
  redIfIncrease?: boolean;
}) {
  if (after === undefined) return null;
  const delta = before !== undefined ? after - before : null;
  const tone =
    (delta !== null && delta < 0n && redIfDecrease) ||
    (delta !== null && delta > 0n && redIfIncrease)
      ? "red"
      : undefined;
  return (
    <Group justify="space-between" gap="xs">
      <Text size="xs" c="dimmed">
        {label}
      </Text>
      <Text size="xs" fw={600} c={tone} ff="monospace">
        {before !== undefined && (
          <Text component="span" size="xs" c="dimmed" mr={6}>
            {formatMoney(before)} →
          </Text>
        )}
        {formatMoney(after)}
        {delta !== null && delta !== 0n && (
          <Text component="span" size="xs" c="dimmed" ml={6}>
            ({delta > 0n ? "+" : ""}
            {formatMoney(delta)})
          </Text>
        )}
      </Text>
    </Group>
  );
}

// Pending captures everything needed to (a) render the confirmation
// modal and (b) actually submit the order if the user confirms. Built
// after validation passes — once stored, the modal opens.
type Pending = {
  request: PlaceSagaRequest;
  heading: string;
  color: string;
  rows: { label: string; value: string }[];
  successTitle: string;
  successMessage: string;
  failureTitle: string;
};

type PlaceResult = { ok: boolean; intent: string; error?: string };

const ACTION_MAP: Record<
  Action,
  { side: Side; positionSide: PositionSide; verb: string; color: string }
> = {
  BUY:   { side: Side.BUY,  positionSide: PositionSide.LONG,  verb: "Buy",   color: "green" },
  SELL:  { side: Side.SELL, positionSide: PositionSide.LONG,  verb: "Sell",  color: "red" },
  SHORT: { side: Side.SELL, positionSide: PositionSide.SHORT, verb: "Short", color: "red" },
  COVER: { side: Side.BUY,  positionSide: PositionSide.SHORT, verb: "Cover", color: "green" },
};

export function OrderForm({
  symbol,
  prefill,
}: {
  symbol: string;
  prefill?: OrderPrefill | null;
}) {
  const [mode, setMode] = useState<Mode>("SINGLE");
  const [action, setAction] = useState<Action>("BUY");
  const [direction, setDirection] = useState<Direction>("LONG");
  const [orderType, setOrderType] = useState<string>("MARKET");
  const [price, setPrice] = useState<number | string>("");
  const [quantity, setQuantity] = useState<number | string>(100);
  const [tif, setTif] = useState<string>("IOC");
  const [takeProfit, setTakeProfit] = useState<number | string>("");
  const [stopLoss, setStopLoss] = useState<number | string>("");
  const [sliceCount, setSliceCount] = useState<number | string>(5);
  const [sliceIntervalSec, setSliceIntervalSec] = useState<number | string>(10);
  const [iceberg, setIceberg] = useState(false);
  const [displayQty, setDisplayQty] = useState<number | string>(10);
  const [stopPrice, setStopPrice] = useState<number | string>("");
  const [trailAmount, setTrailAmount] = useState<number | string>("");
  const [trailMode, setTrailMode] = useState<"AMOUNT" | "BPS">("AMOUNT");
  const [trailLimitOffset, setTrailLimitOffset] = useState<number | string>("");
  const fetcher = useFetcher<PlaceResult>();
  const loading = fetcher.state !== "idle";
  const [pending, setPending] = useState<Pending | null>(null);

  // React to place-saga action completion: surface the success/failure
  // notification using metadata captured on `pending`, then clear it
  // (which also closes the confirmation modal).
  useEffect(() => {
    if (fetcher.state !== "idle" || !fetcher.data || !pending) return;
    const data = fetcher.data;
    if (data.ok) {
      notifications.show({
        title: pending.successTitle,
        message: pending.successMessage,
        color: "green",
      });
      setPending(null);
    } else if (data.error) {
      notifications.show({
        title: pending.failureTitle,
        message: data.error,
        color: "red",
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fetcher.state, fetcher.data]);

  // Apply a fresh prefill — only triggers on nonce change so multiple
  // clicks on the same Close-at-50% menu re-apply even if the values
  // haven't changed. Forces SINGLE mode since prefills are all
  // single-order close-outs.
  useEffect(() => {
    if (!prefill) return;
    setMode("SINGLE");
    setAction(prefill.action);
    setOrderType(prefill.orderType);
    setQuantity(prefill.quantity);
    if (prefill.orderType === "LIMIT") {
      setPrice(prefill.price ?? "");
      setTif("DAY");
    } else {
      setPrice("");
      setTif("IOC");
    }
  }, [prefill?.nonce]);

  const { accountId, margin } = useAccountData();

  const { bids, asks } = useSharedMarketDepth();
  const bestBid = bids[0]?.price;
  const bestAsk = asks[0]?.price;
  const midpoint =
    bestBid !== undefined && bestAsk !== undefined
      ? (bestBid + bestAsk) / 2n
      : undefined;

  const isSingle = mode === "SINGLE";
  const isBracket = mode === "BRACKET";
  const isOCO = mode === "OCO";
  const isTwap = mode === "TWAP";
  const isMarket = orderType === "MARKET";
  const isTrailingMarket = orderType === "TRAILING_STOP_MARKET";
  const isTrailingLimit = orderType === "TRAILING_STOP_LIMIT";
  const isTrailing = isTrailingMarket || isTrailingLimit;

  // Derive (side, position_side) from the user-friendly controls.
  // SINGLE and TWAP use the 4-way action; BRACKET/OCO use the 2-way
  // direction (entry side for bracket, exit side for OCO).
  let side: Side;
  let positionSide: PositionSide;
  if (isSingle || isTwap) {
    const m = ACTION_MAP[action];
    side = m.side;
    positionSide = m.positionSide;
  } else if (isBracket) {
    if (direction === "LONG") {
      side = Side.BUY;
      positionSide = PositionSide.LONG;
    } else {
      side = Side.SELL;
      positionSide = PositionSide.SHORT;
    }
  } else {
    // OCO: exit side. LONG = exit long inventory (sell). SHORT = cover.
    if (direction === "LONG") {
      side = Side.SELL;
      positionSide = PositionSide.LONG;
    } else {
      side = Side.BUY;
      positionSide = PositionSide.SHORT;
    }
  }
  const ps = positionSide;

  // Server-side preview of the order's hold + margin impact. OCO
  // mode doesn't request a preview — exits don't take cash, and the
  // preview's side/position_side don't map cleanly onto an OCO plan.
  // TWAP previews against the worst case (full notional at limit price),
  // matching the server's submit-time buying-power guard.
  const qtyNum = Number(quantity);
  const prcNum = Number(price);
  const previewParams =
    !isOCO && !isTrailing && qtyNum > 0 && (isMarket || prcNum > 0)
      ? {
          accountId,
          symbol,
          side,
          positionSide: ps,
          orderType: isTwap
            ? OrderType.LIMIT
            : (ORDER_TYPES[orderType] ?? OrderType.MARKET),
          price: isMarket && !isTwap ? 0n : moneyToPrice(prcNum),
          quantity: BigInt(qtyNum),
        }
      : null;
  const preview = usePreviewOrderImpact(previewParams);
  const insufficient = preview ? !preview.sufficientBuyingPower : false;

  function handleOrderTypeChange(v: string | null) {
    const next = v ?? "MARKET";
    setOrderType(next);
    if (next === "MARKET" && (tif === "GTC" || tif === "DAY")) {
      setTif("IOC");
    }
    if (next === "LIMIT" && tif === "IOC") {
      setTif("DAY");
    }
  }

  // handleSubmit validates the form and, if everything checks out,
  // stores a Pending record. Setting `pending` opens the confirmation
  // modal — the actual sagaClient.place call happens in executePending.
  function handleSubmit() {
    const qty = typeof quantity === "number" ? quantity : parseInt(quantity, 10);
    if (!qty || qty <= 0) {
      notifications.show({ message: "Enter a valid quantity", color: "red" });
      return;
    }

    if (isTwap) {
      const prc = typeof price === "number" ? price : parseFloat(price);
      if (!prc || prc <= 0) {
        notifications.show({ message: "Enter a valid limit price", color: "red" });
        return;
      }
      const slc = typeof sliceCount === "number" ? sliceCount : parseInt(sliceCount, 10);
      if (!slc || slc <= 0) {
        notifications.show({ message: "Enter a valid slice count", color: "red" });
        return;
      }
      if (slc > qty) {
        notifications.show({
          message: "Slice count cannot exceed total quantity",
          color: "red",
        });
        return;
      }
      const intervalSec =
        typeof sliceIntervalSec === "number"
          ? sliceIntervalSec
          : parseFloat(sliceIntervalSec);
      if (intervalSec < 0) {
        notifications.show({ message: "Slice interval cannot be negative", color: "red" });
        return;
      }
      const verb = ACTION_MAP[action].verb;
      setPending({
        request: {
          $typeName: "saga.v1.PlaceSagaRequest",
          accountId,
          plan: {
            case: "twap",
            value: {
              $typeName: "saga.v1.TWAPPlan",
              symbol,
              side,
              positionSide: ps,
              totalQuantity: BigInt(qty),
              sliceCount: slc,
              sliceIntervalMs: BigInt(Math.round(intervalSec * 1000)),
              limitPrice: moneyToPrice(prc),
            },
          },
        },
        heading: `${verb} TWAP ${qty} ${symbol}`,
        color: ACTION_MAP[action].color,
        rows: [
          { label: "Limit", value: `$${prc.toFixed(4)}` },
          { label: "Slices", value: `${slc} × ${Math.round(qty / slc)} (last ${qty - Math.round(qty / slc) * (slc - 1)})` },
          { label: "Interval", value: `${intervalSec}s` },
          { label: "Window", value: `~${(intervalSec * slc).toFixed(0)}s total` },
        ],
        successTitle: "TWAP placed",
        successMessage: `${verb} TWAP ${qty} ${symbol} over ${slc} slices`,
        failureTitle: "TWAP failed",
      });
      return;
    }

    if (isSingle && isTrailing) {
      const stop = typeof stopPrice === "number" ? stopPrice : parseFloat(stopPrice);
      if (!stop || stop <= 0) {
        notifications.show({ message: "Enter an initial stop price", color: "red" });
        return;
      }
      const trail =
        typeof trailAmount === "number" ? trailAmount : parseFloat(trailAmount);
      if (!trail || trail <= 0) {
        notifications.show({ message: "Enter a trail value > 0", color: "red" });
        return;
      }
      let limOff = 0;
      if (isTrailingLimit) {
        limOff =
          typeof trailLimitOffset === "number"
            ? trailLimitOffset
            : parseFloat(trailLimitOffset);
        if (!limOff || limOff <= 0) {
          notifications.show({
            message: "Trailing-stop-limit requires a positive limit offset",
            color: "red",
          });
          return;
        }
      }
      const verb = ACTION_MAP[action].verb;
      const trailLabel =
        trailMode === "AMOUNT" ? `$${trail.toFixed(4)}` : `${Math.round(trail)} bps`;
      const rows: { label: string; value: string }[] = [
        { label: "Type", value: isTrailingLimit ? "Trailing stop (limit)" : "Trailing stop (market)" },
        { label: "Stop", value: `$${stop.toFixed(4)}` },
        { label: "Trail", value: trailLabel },
      ];
      if (isTrailingLimit) {
        rows.push({ label: "Limit offset", value: `$${limOff.toFixed(4)}` });
      }
      setPending({
        request: {
          $typeName: "saga.v1.PlaceSagaRequest",
          accountId,
          plan: {
            case: "singleOrder",
            value: {
              $typeName: "saga.v1.SingleOrderPlan",
              symbol,
              side,
              orderType: ORDER_TYPES[orderType] ?? OrderType.LIMIT,
              price: 0n,
              stopPrice: moneyToPrice(stop),
              quantity: BigInt(qty),
              displayQuantity: 0n,
              trailAmount: trailMode === "AMOUNT" ? moneyToPrice(trail) : 0n,
              trailOffsetBps: trailMode === "BPS" ? Math.round(trail) : 0,
              limitOffset: isTrailingLimit ? moneyToPrice(limOff) : 0n,
              timeInForce: TimeInForce.GTC,
              positionSide: ps,
              replaceOrderId: "",
            },
          },
        },
        heading: `${verb} ${qty} ${symbol} (trailing)`,
        color: ACTION_MAP[action].color,
        rows,
        successTitle: "Trailing stop placed",
        successMessage: `${verb} trailing ${qty} ${symbol} @ stop $${stop}`,
        failureTitle: "Trailing stop failed",
      });
      return;
    }

    if (isSingle) {
      const prc = typeof price === "number" ? price : parseFloat(price);
      if (!isMarket && (!prc || prc <= 0)) {
        notifications.show({ message: "Enter a valid price", color: "red" });
        return;
      }
      const useIceberg = iceberg && !isMarket && (tif === "GTC" || tif === "DAY");
      let dq = 0;
      if (useIceberg) {
        dq = typeof displayQty === "number" ? displayQty : parseInt(displayQty, 10);
        if (!dq || dq <= 0) {
          notifications.show({ message: "Enter a valid display quantity", color: "red" });
          return;
        }
        if (dq > qty) {
          notifications.show({ message: "Display qty cannot exceed total quantity", color: "red" });
          return;
        }
      }
      const verb = ACTION_MAP[action].verb;
      const priceLabel = isMarket ? "Market" : `$${prc.toFixed(4)}`;
      const rows = [
        { label: "Type", value: orderType },
        { label: "TIF", value: tif },
        { label: isMarket ? "Limit" : "Price", value: priceLabel },
      ];
      if (useIceberg) {
        rows.push({ label: "Iceberg", value: `${dq} displayed of ${qty}` });
      }
      setPending({
        request: {
          $typeName: "saga.v1.PlaceSagaRequest",
          accountId,
          plan: {
            case: "singleOrder",
            value: {
              $typeName: "saga.v1.SingleOrderPlan",
              symbol,
              side,
              orderType: ORDER_TYPES[orderType] ?? OrderType.MARKET,
              price: isMarket ? 0n : moneyToPrice(prc),
              stopPrice: 0n,
              quantity: BigInt(qty),
              displayQuantity: useIceberg ? BigInt(dq) : 0n,
              trailAmount: 0n,
              trailOffsetBps: 0,
              limitOffset: 0n,
              timeInForce: TIME_IN_FORCE[tif] ?? TimeInForce.IOC,
              positionSide: ps,
              replaceOrderId: "",
            },
          },
        },
        heading: `${verb} ${qty} ${symbol}${useIceberg ? " (iceberg)" : ""}`,
        color: ACTION_MAP[action].color,
        rows,
        successTitle: "Order placed",
        successMessage: `${verb} ${qty} ${symbol}`,
        failureTitle: "Order failed",
      });
      return;
    }

    const tp = typeof takeProfit === "number" ? takeProfit : parseFloat(takeProfit);
    const sl = typeof stopLoss === "number" ? stopLoss : parseFloat(stopLoss);
    if (!tp || tp <= 0) {
      notifications.show({ message: "Enter a valid take-profit price", color: "red" });
      return;
    }
    if (!sl || sl <= 0) {
      notifications.show({ message: "Enter a valid stop-loss price", color: "red" });
      return;
    }

    if (isOCO) {
      if (side === Side.SELL && tp <= sl) {
        notifications.show({
          message: "For a SELL OCO, TP must be above SL",
          color: "red",
        });
        return;
      }
      if (side === Side.BUY && tp >= sl) {
        notifications.show({
          message: "For a BUY OCO, TP must be below SL",
          color: "red",
        });
        return;
      }
      const verb = direction === "SHORT" ? "Cover" : "Sell";
      setPending({
        request: {
          $typeName: "saga.v1.PlaceSagaRequest",
          accountId,
          plan: {
            case: "oco",
            value: {
              $typeName: "saga.v1.OCOPlan",
              symbol,
              exitSide: side,
              quantity: BigInt(qty),
              takeProfitPrice: moneyToPrice(tp),
              stopLossPrice: moneyToPrice(sl),
              positionSide: ps,
            },
          },
        },
        heading: `${verb} OCO ${qty} ${symbol}`,
        color: direction === "SHORT" ? "red" : "green",
        rows: [
          { label: "Take Profit", value: `$${tp.toFixed(4)}` },
          { label: "Stop Loss", value: `$${sl.toFixed(4)}` },
        ],
        successTitle: "OCO placed",
        successMessage: `${verb} OCO ${qty} ${symbol} (TP ${tp} / SL ${sl})`,
        failureTitle: "OCO failed",
      });
      return;
    }

    // Bracket mode: entry is always a LIMIT order today.
    const entry = typeof price === "number" ? price : parseFloat(price);
    if (!entry || entry <= 0) {
      notifications.show({ message: "Enter a valid entry price", color: "red" });
      return;
    }
    if (side === Side.BUY && (tp <= entry || sl >= entry)) {
      notifications.show({
        message: "For a long bracket, TP must be above entry and SL below",
        color: "red",
      });
      return;
    }
    if (side === Side.SELL && (tp >= entry || sl <= entry)) {
      notifications.show({
        message: "For a short bracket, TP must be below entry and SL above",
        color: "red",
      });
      return;
    }
    const verb = direction === "SHORT" ? "Short" : "Long";
    setPending({
      request: {
        $typeName: "saga.v1.PlaceSagaRequest",
        accountId,
        plan: {
          case: "bracket",
          value: {
            $typeName: "saga.v1.BracketPlan",
            symbol,
            entrySide: side,
            entryPrice: moneyToPrice(entry),
            entryQuantity: BigInt(qty),
            takeProfitPrice: moneyToPrice(tp),
            stopLossPrice: moneyToPrice(sl),
            positionSide: ps,
          },
        },
      },
      heading: `${verb} bracket ${qty} ${symbol}`,
      color: direction === "SHORT" ? "red" : "green",
      rows: [
        { label: "Entry", value: `$${entry.toFixed(4)}` },
        { label: "Take Profit", value: `$${tp.toFixed(4)}` },
        { label: "Stop Loss", value: `$${sl.toFixed(4)}` },
      ],
      successTitle: "Bracket placed",
      successMessage: `${verb} bracket ${qty} ${symbol} @ ${entry} (TP ${tp} / SL ${sl})`,
      failureTitle: "Bracket failed",
    });
  }

  function executePending() {
    if (!pending) return;
    const fd = new FormData();
    fd.set("intent", "place-saga");
    fd.set("request", toJsonString(PlaceSagaRequestSchema, pending.request));
    fetcher.submit(fd, { method: "post", action: "/trading" });
  }

  // previewBlock is shared between the inline form (live impact while
  // editing) and the confirmation modal (final impact before commit).
  const previewBlock: ReactNode = preview && (
    <Stack gap={4}>
      <ImpactRow
        label="Buying power"
        before={margin?.buyingPower}
        after={
          margin !== null && margin !== undefined
            ? margin.buyingPower - preview.buyingPowerImpact
            : undefined
        }
        redIfDecrease={insufficient}
      />
      {preview.estimatedFillPrice > 0n && (
        <Group justify="space-between" gap="xs">
          <Text size="xs" c="dimmed">
            Est. fill price
          </Text>
          <Text size="xs" fw={600} ff="monospace">
            {formatMoney(preview.estimatedFillPrice)}
            {isMarket && (
              <Text component="span" size="xs" c="dimmed" ml={6}>
                (book-walk avg)
              </Text>
            )}
          </Text>
        </Group>
      )}
      {preview.estimatedFee > 0n && (
        <Group justify="space-between" gap="xs">
          <Text size="xs" c="dimmed">
            Est. fee
          </Text>
          <Text size="xs" fw={600} ff="monospace">
            {formatMoney(preview.estimatedFee)}
            <Text component="span" size="xs" c="dimmed" ml={6}>
              (0.10% of notional)
            </Text>
          </Text>
        </Group>
      )}
      {side === Side.BUY &&
        positionSide === PositionSide.SHORT &&
        preview.estimatedFillPrice > 0n &&
        qtyNum > 0 && (
        <Group justify="space-between" gap="xs">
          <Text size="xs" c="dimmed">
            Cover cost
          </Text>
          <Text size="xs" fw={600} ff="monospace">
            {formatMoney(preview.estimatedFillPrice * BigInt(qtyNum))}
            <Text component="span" size="xs" c="dimmed" ml={6}>
              (paid from short pool)
            </Text>
          </Text>
        </Group>
      )}
      {preview.warnings.map((w) => (
        <Text key={w} size="xs" c="red">
          ⚠ {w}
        </Text>
      ))}
    </Stack>
  );

  return (
    <Card withBorder>
      <Stack gap="sm">
        <Title order={5}>Place Order</Title>
        <SegmentedControl
          fullWidth
          size="xs"
          value={mode}
          onChange={(v) => setMode((v as Mode) ?? "SINGLE")}
          data={[
            { label: "Single", value: "SINGLE" },
            { label: "Bracket", value: "BRACKET" },
            { label: "OCO", value: "OCO" },
            { label: "TWAP", value: "TWAP" },
          ]}
        />
        {isSingle || isTwap ? (
          <SegmentedControl
            fullWidth
            value={action}
            onChange={(v) => setAction(v as Action)}
            data={[
              { label: "Buy", value: "BUY" },
              { label: "Sell", value: "SELL" },
              { label: "Short", value: "SHORT" },
              { label: "Cover", value: "COVER" },
            ]}
            color={ACTION_MAP[action].color}
          />
        ) : (
          <SegmentedControl
            fullWidth
            value={direction}
            onChange={(v) => setDirection(v as Direction)}
            data={[
              { label: "Long", value: "LONG" },
              { label: "Short", value: "SHORT" },
            ]}
            color={direction === "SHORT" ? "red" : "green"}
          />
        )}
        {isSingle && (
          <Group grow>
            <Select
              label="Type"
              size="xs"
              value={orderType}
              onChange={handleOrderTypeChange}
              data={[
                { label: "Limit", value: "LIMIT" },
                { label: "Market", value: "MARKET" },
                { label: "Trailing stop (market)", value: "TRAILING_STOP_MARKET" },
                { label: "Trailing stop (limit)", value: "TRAILING_STOP_LIMIT" },
              ]}
              checkIconPosition="right"
            />
            <Select
              label="TIF"
              size="xs"
              value={tif}
              onChange={(v) => setTif(v ?? "IOC")}
              data={isMarket ? MARKET_TIF_OPTIONS : LIMIT_TIF_OPTIONS}
              checkIconPosition="right"
              disabled={isTrailing}
            />
          </Group>
        )}
        {((isSingle && !isMarket && !isTrailing) || isBracket || isTwap) && (
          <Stack gap={4}>
            <NumberInput
              label={isBracket ? "Entry Price" : isTwap ? "Limit Price" : "Price"}
              size="xs"
              placeholder="0.00"
              min={0}
              decimalScale={4}
              value={price}
              onChange={setPrice}
            />
            {isSingle && !isMarket && (
              <Button.Group>
                <Button
                  size="compact-xs"
                  variant="default"
                  fullWidth
                  disabled={bestBid === undefined}
                  onClick={() =>
                    bestBid !== undefined && setPrice(priceToNumber(bestBid))
                  }
                >
                  Bid {bestBid === undefined ? "—" : formatPrice(bestBid)}
                </Button>
                <Button
                  size="compact-xs"
                  variant="default"
                  fullWidth
                  disabled={midpoint === undefined}
                  onClick={() =>
                    midpoint !== undefined && setPrice(priceToNumber(midpoint))
                  }
                >
                  Mid {midpoint === undefined ? "—" : formatPrice(midpoint)}
                </Button>
                <Button
                  size="compact-xs"
                  variant="default"
                  fullWidth
                  disabled={bestAsk === undefined}
                  onClick={() =>
                    bestAsk !== undefined && setPrice(priceToNumber(bestAsk))
                  }
                >
                  Ask {bestAsk === undefined ? "—" : formatPrice(bestAsk)}
                </Button>
              </Button.Group>
            )}
          </Stack>
        )}
        {isSingle && isTrailing && (
          <Stack gap={4}>
            <NumberInput
              label="Initial stop price"
              description={
                action === "BUY" || action === "COVER"
                  ? "Trailing-stop BUY ratchets DOWN as mark falls."
                  : "Trailing-stop SELL ratchets UP as mark rises."
              }
              size="xs"
              placeholder="0.00"
              min={0}
              decimalScale={4}
              value={stopPrice}
              onChange={setStopPrice}
            />
            <SegmentedControl
              size="xs"
              value={trailMode}
              onChange={(v) => setTrailMode(v as "AMOUNT" | "BPS")}
              data={[
                { label: "$ amount", value: "AMOUNT" },
                { label: "bps", value: "BPS" },
              ]}
            />
            <NumberInput
              label={trailMode === "AMOUNT" ? "Trail amount ($)" : "Trail (bps)"}
              size="xs"
              placeholder={trailMode === "AMOUNT" ? "0.50" : "50"}
              min={0}
              decimalScale={trailMode === "AMOUNT" ? 4 : 0}
              value={trailAmount}
              onChange={setTrailAmount}
            />
            {isTrailingLimit && (
              <NumberInput
                label="Limit offset ($)"
                description="Limit price = stop ± this offset at trigger."
                size="xs"
                placeholder="0.10"
                min={0}
                decimalScale={4}
                value={trailLimitOffset}
                onChange={setTrailLimitOffset}
              />
            )}
          </Stack>
        )}
        <NumberInput
          label={isTwap ? "Total Quantity" : "Quantity"}
          size="xs"
          placeholder="0"
          min={1}
          allowDecimal={false}
          value={quantity}
          onChange={setQuantity}
        />
        {isSingle && !isMarket && !isTrailing && (tif === "GTC" || tif === "DAY") && (
          <Stack gap={4}>
            <Switch
              size="xs"
              label="Iceberg (hide reserve)"
              checked={iceberg}
              onChange={(e) => setIceberg(e.currentTarget.checked)}
            />
            {iceberg && (
              <NumberInput
                label="Displayed quantity"
                description="Slice exposed to the book; the rest stays hidden until each slice fills."
                size="xs"
                placeholder="10"
                min={1}
                allowDecimal={false}
                value={displayQty}
                onChange={setDisplayQty}
              />
            )}
          </Stack>
        )}
        {isTwap && (
          <Group grow>
            <NumberInput
              label="Slices"
              size="xs"
              placeholder="5"
              min={1}
              allowDecimal={false}
              value={sliceCount}
              onChange={setSliceCount}
            />
            <NumberInput
              label="Interval (s)"
              size="xs"
              placeholder="10"
              min={0}
              decimalScale={1}
              value={sliceIntervalSec}
              onChange={setSliceIntervalSec}
            />
          </Group>
        )}
        {(isBracket || isOCO) && (
          <Group grow>
            <NumberInput
              label="Take Profit"
              size="xs"
              placeholder="0.00"
              min={0}
              decimalScale={4}
              value={takeProfit}
              onChange={setTakeProfit}
            />
            <NumberInput
              label="Stop Loss"
              size="xs"
              placeholder="0.00"
              min={0}
              decimalScale={4}
              value={stopLoss}
              onChange={setStopLoss}
            />
          </Group>
        )}
        {previewBlock}
        <Button
          fullWidth
          color={
            isSingle || isTwap
              ? ACTION_MAP[action].color
              : direction === "SHORT"
                ? "red"
                : "green"
          }
          onClick={handleSubmit}
          disabled={insufficient}
        >
          {isSingle && `${ACTION_MAP[action].verb} ${symbol}`}
          {isBracket && `${direction === "SHORT" ? "Short" : "Long"} bracket ${symbol}`}
          {isOCO && `${direction === "SHORT" ? "Cover" : "Sell"} OCO ${symbol}`}
          {isTwap && `${ACTION_MAP[action].verb} TWAP ${symbol}`}
        </Button>
      </Stack>

      <Modal
        opened={pending !== null}
        onClose={() => !loading && setPending(null)}
        title="Confirm order"
        centered
      >
        {pending && (
          <Stack gap="sm">
            <Title order={4} c={pending.color}>
              {pending.heading}
            </Title>
            <Stack gap={4}>
              {pending.rows.map((r) => (
                <Group key={r.label} justify="space-between" gap="xs">
                  <Text size="sm" c="dimmed">
                    {r.label}
                  </Text>
                  <Text size="sm" fw={600} ff="monospace">
                    {r.value}
                  </Text>
                </Group>
              ))}
            </Stack>
            {previewBlock}
            <Group justify="flex-end" gap="xs" mt="xs">
              <Button
                variant="default"
                disabled={loading}
                onClick={() => setPending(null)}
              >
                Cancel
              </Button>
              <Button
                color={pending.color}
                loading={loading}
                onClick={executePending}
              >
                Confirm
              </Button>
            </Group>
          </Stack>
        )}
      </Modal>
    </Card>
  );
}
