ALTER TABLE projection_orders
    ADD COLUMN IF NOT EXISTS display_quantity    BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS displayed_remaining BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS trail_amount        BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS trail_offset_bps    INT    NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS limit_offset        BIGINT NOT NULL DEFAULT 0;

ALTER TABLE projection_pending_orders
    ADD COLUMN IF NOT EXISTS display_quantity BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS trail_amount     BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS trail_offset_bps INT    NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS limit_offset     BIGINT NOT NULL DEFAULT 0;
